version: '2'

services:
  db:
    image: mysql:5.7
    container_name: wordpress_mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    networks:
      - layout_optimizer_network
  wordpress:
    image: wordpress:latest
    container_name: wordpress_server
    volumes:
      - .:/var/www/html/wp-content/plugins/layout-optimizer
    depends_on:
      - db
    ports:
      - "8000:80"
      - "80:80"
    restart: always
    env_file: .env
    networks:
      - layout_optimizer_network

volumes:
  db_data:
    driver: local
networks:
  layout_optimizer_network:
