version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
  wordpress:
    # image: wordpress:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/wp-content/plugins/layout-optimizer
      - for-testing:/tmp
    depends_on:
      - db
    ports:
      - "8000:80"
      - "80:80"
    restart: always
    env_file: .env
volumes:
  db_data:
    driver: local
  for-testing:
    driver: local
